[package]
name = "qrbrand"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
qrcode = "0.14"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
anyhow = "1.0"
url = "2.5"
rusttype = "0.9"


